name: map_n_mark
description: "attendance app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  supabase_flutter: ^2.10.3
  qr_flutter: ^4.1.0
  geolocator: ^13.0.0
  intl: ^0.19.0
  mobile_scanner: ^5.1.0
  google_maps_flutter: ^2.14.0
  fl_chart: ^0.70.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
